---
title: "Extended Data Figure 5"
author: '`r Sys.info()["user"]`'
date: '`r format(Sys.time(), "%B %d, %Y %H:%M:%S %Z")`'
output:
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    highlight: pygments
    df_print: kable
params:
  sample_name: ~
  sample_path: ~
  out_rds_path: ~
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(
	echo=TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png", "jpeg", "pdf")
)
```




```{r lib}
library(hdf5r)
library(Seurat)
library(SoupX)
library(canceRbits)
library(dplyr)
library(patchwork)
library(DT)
library(Azimuth)
library(SCpubr)
library(tibble)
library(dittoSeq)
library(scRepertoire)
library(reshape2)
library(viridis)
library(grDevices)
library(ggpubr)
library(ggplot2)

```



# Open corrected counts and annotated seurat object
Load the corrected (SoupX), normalized (SCTransformed) and annotated (Twice mapped - Tabula Sapiens Skin reference and PBMC azimuth reference) data.
```{r echo=TRUE, message=FALSE, warning=FALSE, out.width='100%'}
srat <- readRDS( "20241005_Ressler2024_NeoBCC.Rds")
meta <- srat@meta.data
meta$WHO <- "SD"
meta$WHO[meta$patient %in% c("NeoBCC007_post", "NeoBCC008_post", "NeoBCC012_post", "NeoBCC017_post")] <- "CR"
meta$WHO[meta$patient %in% c("NeoBCC004_post", "NeoBCC006_post", "NeoBCC010_post", "NeoBCC011_post")] <- "PR"
srat <- AddMetaData(srat, meta$WHO, col.name = "WHO")
srat$WHO <- factor(srat$WHO, levels = c("CR", "PR", "SD"))
```

#Define levels and colors


```{r echo=TRUE, fig.height=25, fig.width=25, message=FALSE, warning=FALSE, out.width='100%'}
srat@meta.data$anno_l1 <- factor(srat@meta.data$anno_l1, levels=c("other",
                                                                 "Mast cells",
                                                                 "Mono-Mac",
                                                                 "LC",
                                                                 "DC",
                                                                 "pDC",
                                                                 "Plasma cells",
                                                                 "B cells" ,
                                                                 "Proliferating cells",
                                                                 "Natural killer cells",
                                                                 "CD8+ T cells",
                                                                 "Tregs",
                                                                  "CD4+ T cells" ,
                                                                 "Melanocytes",
                                                                 "Endothelial cells",
                                                                 "Fibroblasts",
                                                                 "Keratinocytes",
                                                                 "Malignant cells"))

# Subset immune / non-immune cells
imm <- subset(srat, subset = anno_l1 %in% c("other",
                                                                 "Mast cells",
                                                                 
                                                                 "Mono-Mac",
                                                                 "LC",
                                                                 "DC",
                                                                 "pDC",
                                                                 "Plasma cells",
                                                                 "B cells" ,
                                                                 "Proliferating cells",
                                                                 "Natural killer cells",
                                                                 "CD8+ T cells",
                                                                 "Tregs",
                                                                  "CD4+ T cells" ))
imm$anno_l1 <- droplevels(imm$anno_l1)


```


# Extended Data Figure 5B

```{r fig.height=12, fig.width=40, message=FALSE, warning=FALSE, out.width='100%'}

df <- imm@meta.data %>%
  mutate_if(sapply(imm@meta.data, is.character), as.factor)  %>% 
  group_by( Pathological.Response, patient, anno_l1,    .drop = FALSE)%>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(percent = Nb/C*100) %>%
  filter(percent != "NaN") %>%
  arrange(Pathological.Response, percent)


tmp <- df[df$anno_l1 %in% c("Mono-Mac", "LC", "DC", "pDC", "Mast cells"),]


p1 <- ggpaired(tmp, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         palette= c("yellow", "#fec44f"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))





tmp <- df[df$anno_l1 %in% c("Plasma cells", "B cells"),]


p2 <- ggpaired(tmp, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         palette= c("#7bccc4", "#35978f"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))



 

tmp <- df[df$anno_l1 %in% c("CD8+ T cells"),]


p3 <- ggpaired(tmp, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         palette= c("#fa9fb5", "#df65b0"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5))+ ylim(c(0,60))

tmp <- df[df$anno_l1 %in% c("Tregs"),]


p4 <- ggpaired(tmp, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         palette= c("#ae017e", "#49006a"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))


tmp <- df[df$anno_l1 %in% c("CD4+ T cells"),]


p5 <- ggpaired(tmp, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         palette= c("#41ab5d", "#016c59"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))

p <- p1 + p2 + p3 + p4 + p5 + plot_layout(ncol=5, widths = c(1/2, 1/5, 1/10, 1/10, 1/10), guides= "collect") & NoLegend()

p


p1 <-  ggpaired(df, 
         x = "Pathological.Response", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "Pathological.Response" , 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("pCR", "non-pCR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))


DT::datatable(p1$data, 
              caption = ("Extended Data Figure 5B"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```



# Extended Data Figure 5D

```{r fig.height=10, fig.width=40, message=FALSE, warning=FALSE, out.width='100%'}

df <- imm@meta.data %>%
  mutate_if(sapply(imm@meta.data, is.character), as.factor)  %>% 
  group_by( WHO, patient, anno_l1,    .drop = FALSE)%>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(percent = Nb/C*100) %>%
  filter(percent != "NaN") %>%
  arrange(WHO, percent)


tmp <- df[df$anno_l1 %in% c("Mono-Mac", "LC", "DC", "pDC", "Mast cells"),]


p1 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white","yellow", "#fec44f"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))





tmp <- df[df$anno_l1 %in% c("Plasma cells", "B cells"),]


p2 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white","#7bccc4", "#35978f"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))



 

tmp <- df[df$anno_l1 %in% c("CD8+ T cells"),]


p3 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white","#fa9fb5", "#df65b0"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5))+ ylim(c(0,60))

tmp <- df[df$anno_l1 %in% c("Tregs"),]


p4 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white","#ae017e", "#49006a"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5) + 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))


tmp <- df[df$anno_l1 %in% c("CD4+ T cells"),]


p5 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white","#41ab5d", "#016c59"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))

p <- p1 + p2 + p3 + p4 + p5 + plot_layout(ncol=5, widths = c(1/2, 1/5, 1/10, 1/10, 1/10), guides= "collect") & NoLegend()

p


p1 <-  ggpaired(df, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         facet.by = "anno_l1", 
         color = "black", 
         fill = "WHO" , 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)", ncol = 5)+ 
  stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = c(55, 50, 50), hide.ns = FALSE, label = "p.signif",  bracket.size = 0.5,tip.length = 0.01 ,comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size =4)   +
  theme(text = element_text(size = 24),axis.text.x = element_text(angle = 90,  vjust=0.5)) + ylim(c(0,60))


DT::datatable(p1$data, 
              caption = ("Extended Data Figure 5D"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```

