---
title: "B and Plasma cells analysis"
author: '`r Sys.info()["user"]`'
date: '`r format(Sys.time(), "%B %d, %Y %H:%M:%S %Z")`'
output:
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    highlight: pygments
    df_print: kable
params:
  sample_name: ~
  sample_path: ~
  out_rds_path: ~
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo=TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png", "jpeg", "pdf")
)
```


# Setup

```{r lib}
library(hdf5r)
library(Seurat)
library(SoupX)
library(canceRbits)
library(dplyr)
library(patchwork)
library(DT)
library(Azimuth)
library(SCpubr)
library(tibble)
library(dittoSeq)
library(scRepertoire)
library(reshape2)
library(viridis)
library(grDevices)
library(ggpubr)
library(ggplot2)

```

```{r}
# path to data, to be adapted - serve here to get raw data
path_to_data = paste0(Sys.getenv("DATA"),"/neoBCC29032022/biomedical-sequencing.at/projects/BSA_0460_MF_BCC_1ab413522d3e4d2d959b1b8f2681cf06/COUNT/")


# Load seurat object containing single cell pre-processed and annotated data, in the metadata folder

srat <- readRDS( "20241005_Ressler2024_NeoBCC.Rds")
meta <- srat@meta.data
meta$WHO <- "SD"
meta$WHO[meta$patient %in% c("NeoBCC007_post", "NeoBCC008_post", "NeoBCC012_post", "NeoBCC017_post")] <- "CR"
meta$WHO[meta$patient %in% c("NeoBCC004_post", "NeoBCC006_post", "NeoBCC010_post", "NeoBCC011_post")] <- "PR"
srat <- AddMetaData(srat, meta$WHO, col.name = "WHO")
srat$WHO <- factor(srat$WHO, levels = c("CR", "PR", "SD"))


library('canceRbits')
library(Seurat)
library('patchwork')
library(dplyr)
library(tidyverse)
library(RColorBrewer)
library(DT)
library(viridis)
library(scales)
library(dittoSeq)
library(ggpubr)
library(enrichplot)
library(clusterProfiler)
library("org.Hs.eg.db")
library(DOSE)
library(ggnewscale)
library(msigdbr)
library(scRepertoire)
library(reshape2)

SETUP_TIME <- proc.time()['elapsed']



```



# Figure 3A
```{r  echo=TRUE, fig.height=4, fig.width=4, out.width='100%'}

s   <- subset(srat, subset = anno_l1 %in% c("B cells","Plasma cells"))




s@meta.data$seurat_clusters <- factor(s@meta.data$seurat_clusters, levels=c("34","7", "21",  "38",
                                                                             "15", "22","3", "4", "18"))
                                      
                                      
                                  
colors_B <- c(
  "34" = "#ae017e",
  "7"  =  "#377eb8",
  "21" =  "#f781bf",  
  "38" = "#fed976",
  "15" = "#a6cee3" ,
  "22" = "#e31a1c"   ,
   "3" = "#9e9ac8",
 "4"   = "#fdb462" ,
 "18"  = "#b3de69"
)

                                                                 



p <- SCpubr::do_DimPlot(sample = s, 
                   reduction = "umap", 
                   label = TRUE, 
                   repel = TRUE, 
                   label.color = "black", 
                   legend.position = "none", 
                   group.by = "seurat_clusters", 
                   font.size = 25,
                   pt.size = 0.5, 
                   colors.use = colors_B) + theme_minimal()  + NoLegend() + theme(text = element_text(size=20))

p

DT::datatable(p$data, 
              caption = ("Figure 3A"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```



# Figure 3B

```{r Fig2_bubblePlot_v1, echo=TRUE, fig.height=10, fig.width=16, message=FALSE, warning=FALSE, out.width='100%'}
Idents(s) <- s$seurat_clusters

               
genes <- list( 
               "B" = c("MS4A1", "CD19"                       ),
               "Ag presentation" = c("HLA-DRA", "HLA-DRB1", "HLA-DPB1", "CD40"),
               "Cytotox" = c("GZMK", "PRF1"),
               "Mem" = "CD27",
               "Plasma" = c("IGKC", "IGHG1", "CD38", "SDC1", "JCHAIN"),
               "Cell state" = c(  "G2M.Score", "S.Score","percent.mito")
               
               )

p <- SCpubr::do_DotPlot(sample = s, 
                        features = genes, 
                        font.size = 18, 
                        legend.length = 12,  
                        legend.type = "colorbar", 
                        dot.scale = 8,  
                        colors.use = c("#7fbc41","#b8e186", "#f7f7f7","#fde0ef", "#c51b7d"))

p
DT::datatable(p$data, 
              caption = ("Figure 3B"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```



# Figure 3C


```{r Fig3_B_BarPlot_patient_response, fig.height=8, fig.width=12, message=FALSE, warning=FALSE,  out.width='100%'}


q1 <- SCpubr::do_BarPlot( s,
                         group.by = "seurat_clusters",
                         split.by = "WHO",
                         position = "fill",
                         flip = TRUE,
                         order=FALSE,
                         legend.position = "none",
                         font.size = 32 ,
                         colors.use = colors_B,
                         xlab = "",
                         ylab = ""
                          
                   ) + xlab("Response") + ylab("% of B and plasma cells")



q1
DT::datatable(q1$data, 
              caption = ("Figure 3C"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```


# Figure 3D

```{r  echo=TRUE, fig.height=6, fig.width=5, message=FALSE, warning=FALSE, out.width='100%'}

p1 <- Seurat::VlnPlot(s, 
                     features = "HLA-DRA", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p1 <- p1 + geom_boxplot(width=0.3, fill="white")

f1 <- SCpubr::do_FeaturePlot(s, 
                     features = "HLA-DRA", legend.position = "right", legend.length = 4)


p2 <- Seurat::VlnPlot(s, 
                     features = "GZMK", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p2 <- p2 + geom_boxplot(width=0.3, fill="white")

f2 <- SCpubr::do_FeaturePlot(s, 
                     features = "GZMK", legend.position = "right", legend.length = 4)



p3 <- Seurat::VlnPlot(s, 
                     features = "CD27", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p3 <- p3 + geom_boxplot(width=0.3, fill="white")

f3 <- SCpubr::do_FeaturePlot(s, 
                     features = "CD27", legend.position = "right", legend.length = 4)


p4 <- Seurat::VlnPlot(s, 
                     features = "XBP1", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p4 <- p4 + geom_boxplot(width=0.3, fill="white")

f4 <- SCpubr::do_FeaturePlot(s, 
                     features = "XBP1", legend.position = "right", legend.length = 4)



c1 <- f1+p1  + plot_layout(ncol = 2,  widths   = c(1,2)) 
c2 <- f2+p2  + plot_layout(ncol = 2,  widths   = c(1,2))
c3 <- f3+p3  + plot_layout(ncol = 2,  widths   = c(1,2))
c4 <- f4+p4  + plot_layout(ncol = 2,  widths   = c(1,2))

c1
DT::datatable(f1$data, 
              caption = ("Figure 3Da_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
c2
DT::datatable(f2$data, 
              caption = ("Figure 3Db_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
c3
DT::datatable(f3$data, 
              caption = ("Figure 3Dc_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
c4
DT::datatable(f4$data, 
              caption = ("Figure 3Dd_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

DT::datatable(p1$data, 
              caption = ("Figure 3Da_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

DT::datatable(p2$data, 
              caption = ("Figure 3Db_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
DT::datatable(p3$data, 
              caption = ("Figure 3Dc_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
DT::datatable(p4$data, 
              caption = ("Figure 3Dd_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```












# Extended Data Figure 9

```{r Fig3_B_BoxPlot_Response, fig.height=6, fig.width=30, message=FALSE, warning=FALSE, out.width='100%'}

s$WHO <- factor(s$WHO, levels = c("CR","PR","SD"))
df <- s@meta.data %>%
    mutate_if(sapply(s@meta.data, is.character), as.factor)  %>% 
    group_by( WHO, patient, seurat_clusters,    .drop = FALSE)%>% 
  summarise(Nb = n()) %>%
  mutate(C = sum(Nb)) %>%
  mutate(percent = Nb/C*100) %>%
  filter(percent != "NaN") %>%
  arrange(WHO, percent)




tmp <- df[df$seurat_clusters %in% c("34"),]


p1 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#dd3497", "#ae017e"), 
         point.size = 2, 
         xlab = "", 
         ylab = "Percentage (%)") + 
  ylim(c(0,90)) +
   ggtitle("C34") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 



tmp <- df[df$seurat_clusters %in% c("7"),]


p2 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#1d91c0", "#253494"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
   ggtitle("C7") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 

tmp <- df[df$seurat_clusters %in% c("21"),]


p3 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" ,  
         
         palette= c("white", "#fde0dd", "#fa9fb5"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
   ggtitle("C21") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 

tmp <- df[df$seurat_clusters %in% c("38"),]


p4 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#ffffcc", "yellow"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") +
  ylim(c(0,90)) +
   ggtitle("C38") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 


tmp <- df[df$seurat_clusters %in% c("15"),]


p5 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#deebf7", "#9ecae1"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
   ggtitle("C15") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 

tmp <- df[df$seurat_clusters %in% c("22"),]


p6 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#fc9272", "#ef3b2c"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
  ggtitle("C22") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 


tmp <- df[df$seurat_clusters %in% c("3"),]


p7 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#decbe4", "#c2a5cf"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
  ggtitle("C3") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 

tmp <- df[df$seurat_clusters %in% c("4"),]


p8 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#fee0b6", "#fec44f"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
  ggtitle("C4") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 


tmp <- df[df$seurat_clusters %in% c("18"),]


p9 <- ggpaired(tmp, 
         x = "WHO", 
         y = "percent", 
         id="patient", 
         color = "black", 
         fill = "WHO" , 
         palette= c("white", "#b8e186", "#7fbc41"), 
         point.size = 2, 
         xlab = "", 
         ylab = "") + 
  ylim(c(0,90)) +
  ggtitle("C18") + NoLegend() +
  stat_compare_means( method = "wilcox.test", 
                      paired = FALSE, 
                      label.y = 80, 
                      hide.ns = FALSE, 
                      label = "p.signif", 
                      label.x.npc = "center", 
                      bracket.size = 1, 
                      comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), 
                      size = 8)  +
  theme(text = element_text(size = 18),axis.text.x = element_text(angle = 90,  vjust=0.5)) 

p <- p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + p9 + plot_layout(nrow = 1, guides = "collect")
p

DT::datatable(rbind(p1$data, p2$data, p3$data, p4$data, p5$data, p6$data, p7$data, p8$data, p9$data), 
              caption = ("Extended Data Figure 9A"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```

# Extended Data Figure 9B

```{r  echo=TRUE, fig.height=10, fig.width=10, message=FALSE, warning=FALSE, out.width='100%'}

p1 <- Seurat::VlnPlot(s, 
                     features = "PRF1", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p1 <- p1 + geom_boxplot(width=0.3, fill="white")

f1 <- SCpubr::do_FeaturePlot(s, 
                     features = "PRF1", legend.position = "right", legend.length = 4)


p2 <- Seurat::VlnPlot(s, 
                     features = "IL10", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p2 <- p2 + geom_boxplot(width=0.3, fill="white")

f2 <- SCpubr::do_FeaturePlot(s, 
                     features = "IL10", legend.position = "right", legend.length = 4)



p3 <- Seurat::VlnPlot(s, 
                     features = "TGFB1", 
                     group.by = "seurat_clusters", 
                     pt.size = 0,  
                     cols = colors_B) & NoLegend() 
p3 <- p3 + geom_boxplot(width=0.3, fill="white")

f3 <- SCpubr::do_FeaturePlot(s, 
                     features = "TGFB1", legend.position = "right", legend.length = 4)





c1 <- f1+p1  + plot_layout(ncol = 1,  heights =  c(1,1)) 
c2 <- f2+p2  + plot_layout(ncol = 1,  heights = c(1,1))
c3 <- f3+p3  + plot_layout(ncol = 1,  heights = c(1,1))

c1
DT::datatable(f1$data, 
              caption = ("ExtendedData_Figure9Ba_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

DT::datatable(p1$data, 
              caption = ("ExtendedData_Figure9Ba_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

c2
DT::datatable(f2$data, 
              caption = ("ExtendedData_Figure9Bb_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

DT::datatable(p2$data, 
              caption = ("ExtendedData_Figure9Bb_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
c3
DT::datatable(f3$data, 
              caption = ("ExtendedData_Figure9Bc_FeaturePlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))



DT::datatable(p3$data, 
              caption = ("ExtendedData_Figure9Bc_VlnPlot"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```

# Figure 3E

```{r}
# scRepertoire functions
#Use to shuffle between chains
off.the.chain <- function(dat, chain, cloneCall) {
  chain1 <- toupper(chain) #to just make it easier
  if (chain1 %in% c("TRA", "TRD", "IGH")) {
    x <- 1
  } else if (chain1 %in% c("TRB", "TRG", "IGL")) {
    x <- 2
  } else {
    warning("It looks like ", chain, " does not match the available options for `chain = `")
  }
  dat[,cloneCall] <- str_split(dat[,cloneCall], "_", simplify = TRUE)[,x]
  return(dat)
}


#Remove list elements that contain all NA values
checkBlanks <- function(df, cloneCall) {
    for (i in seq_along(df)) {
        if (length(df[[i]][,cloneCall]) == length(which(is.na(df[[i]][,cloneCall]))) | 
            length(which(!is.na(df[[i]][,cloneCall]))) == 0 | 
            nrow(df[[i]]) == 0) {
            df[[i]] <- NULL
        } else {
            next()
        }
    }
    return(df)
}


#Ensure df is in list format
checkList <- function(df) {
    df <- if(is(df)[1] != "list") list(df) else df
    return(df)
}

checkContigs <- function(df) {
  df <- lapply(seq_len(length(df)), function(x) {
    df[[x]] <- if(is(df[[x]])[1] != "data.frame") as.data.frame(df[[x]]) else df[[x]]
    df[[x]][df[[x]] == ""] <- NA
    df[[x]] <- df[[x]][with(df[[x]], order(reads, chain)),]
  })
}

#' @importFrom dplyr bind_rows
bound.input.return <- function(df) {
  if (inherits(x=df, what ="Seurat") | inherits(x=df, what ="SummarizedExperiment")) {
    df <- grabMeta(df)
  } else {
    df <- bind_rows(df, .id = "element.names")
  }
  return(df)
}

list.input.return <- function(df, split.by) {
  if (inherits(x=df, what ="Seurat") | inherits(x=df, what ="SummarizedExperiment")) {
    if(is.null(split.by)){
      split.by <- "cluster"
    }
    df <- expression2List(df, split.by)
  } 
  return(df)
}

#Get UMAP or other coordinates
#' @importFrom SingleCellExperiment reducedDim
get.coord <- function(sc, reduction) { 
  if (is.null(reduction)) {
    reduction = "pca"
  }
  if (inherits(x=sc, what ="Seurat")) {
    coord <- sc@reductions[[reduction]]@cell.embeddings
  } else if (inherits(x=sc, what ="SummarizedExperiment")) {
    coord <- reducedDim(sc, reduction)
  }
  return(coord)
}

#This is to check the single-cell expression object
checkSingleObject <- function(sc) {
    if (!inherits(x=sc, what ="Seurat") &&
        !inherits(x=sc, what ="SummarizedExperiment")){
        stop("Object indicated is not of class 'Seurat' or 
            'SummarizedExperiment', make sure you are using
            the correct data.") }
    }

#This is to grab the meta data from a seurat or SCE object
#' @importFrom SingleCellExperiment colData 
grabMeta <- function(sc) {
    if (inherits(x=sc, what ="Seurat")) {
        meta <- data.frame(sc[[]], slot(sc, "active.ident"))
        if ("cluster" %in% colnames(meta)) {
          colnames(meta)[length(meta)] <- "cluster.active.ident"
        } else {
        colnames(meta)[length(meta)] <- "cluster"
        }
    }
    else if (inherits(x=sc, what ="SummarizedExperiment")){
        meta <- data.frame(colData(sc))
        rownames(meta) <- sc@colData@rownames
        clu <- which(colnames(meta) == "ident")
        if ("cluster" %in% colnames(meta)) {
          colnames(meta)[clu] <- "cluster.active.idents"
        } else {
          colnames(meta)[clu] <- "cluster"
        }
    }
    return(meta)
}

#This is to add the sample and ID prefixes for combineBCR()/TCR()
modifyBarcodes <- function(df, samples, ID) {
    out <- NULL
    for (x in seq_along(df)) {
        data <- df[[x]] 
        if (!is.null(ID)){
          data$barcode <- paste0(samples[x], "_", ID[x], "_", data$barcode)
        } else {
          data$barcode <- paste0(samples[x], "_", data$barcode)
        }
        out[[x]] <- data }
    return(out)
}

#Removing barcodes with NA recovered
removingNA <- function(final) {
    for(i in seq_along(final)) {
        final[[i]] <- na.omit(final[[i]])}
    return(final)
}

#Removing barcodes with > 2 clones recovered
removingMulti <- function(final){
    for(i in seq_along(final)) {
        final[[i]] <- filter(final[[i]], !grepl(";",CTnt))}
    return(final)
}

#Removing extra clonotypes in barcodes with > 2 productive contigs
#' @import dplyr
filteringMulti <- function(x) {
    x <- x %>%
      group_by(barcode, chain) %>% 
      slice_max(n = 1, order_by = reads)
    table <- subset(as.data.frame(table(x$barcode)), Freq > 2)
    if (nrow(table) > 0) {
      barcodes <- as.character(unique(table$Var1))
      multichain <- NULL
      for (j in seq_along(barcodes)) {
        chain <- x[x$barcode == barcodes[j],] %>% 
            group_by(barcode) %>% top_n(n = 2, wt = reads)
        multichain <- rbind(multichain, chain) 
        }
    x <- subset(x, barcode %!in% barcodes)
    x <- rbind(x, multichain) 
    }
    return(x)
}



#Filtering NA contigs out of single-cell expression object
#' @import dplyr
#' @importFrom SingleCellExperiment colData
filteringNA <- function(sc) {
    meta <- grabMeta(sc)
    evalNA <- data.frame(meta[,"cloneType"])
    colnames(evalNA) <- "indicator"
    evalNA <- evalNA %>%
        transmute(indicator = ifelse(is.na(indicator), 0, 1))
    rownames(evalNA) <- rownames(meta)
    if (inherits(x=sc, what ="cell_data_set")){
      colData(sc)[["evalNA"]]<-evalNA
      return(sc[, !is.na(sc$cloneType)])
    }else{
      col.name <- names(evalNA) %||% colnames(evalNA)
      sc[[col.name]] <- evalNA
      sc <- subset(sc, cloneType != 0)
      return(sc)
    }
}

#Calculating diversity using Vegan R package
#' @importFrom vegan diversity estimateR
diversityCall <- function(data) {
    w <- diversity(data[,"Freq"], index = "shannon")
    x <- diversity(data[,"Freq"], index = "invsimpson")
    y <- estimateR(data[,"Freq"])[2] #Chao
    z <- estimateR(data[,"Freq"])[4] #ACE
    z2 <- diversity(data[,"Freq"], index = "shannon")/log(length(data[,"Freq"]))
    out <- c(w,x,y,z, z2)
    return(out)
}

#Organizing list of contigs for visualization
parseContigs <- function(df, i, names, cloneCall) {
    data <- df[[i]]
    data1 <- data %>% group_by(data[,cloneCall]) %>%
        summarise(Abundance=n())
    colnames(data1)[1] <- cloneCall
    data1$values <- names[i]
    return(data1)
}

#Calculate the Morisita Index for Overlap Analysis
#' @author Massimo Andreatta, Nick Borcherding
morisitaIndex <- function(df, length, cloneCall, coef_matrix) {
    for (i in seq_along(length)){
        df.i <- df[[i]]
        df.i <- data.frame(table(df.i[,cloneCall]))
        colnames(df.i) <- c(cloneCall, 'Count')
        df.i[,2] <- as.numeric(df.i[,2])
        for (j in seq_along(length)){
            if (i >= j){ next }
            else { df.j <- df[[j]]
            df.j <- data.frame(table(df.j[,cloneCall]))
            colnames(df.j) <- c(cloneCall, 'Count')
            df.j[,2] <- as.numeric(df.j[,2])
            merged <- merge(df.i, df.j, by = cloneCall, all = TRUE)
            merged[is.na(merged)] <- 0
            X <- sum(merged[,2])
            Y <- sum(merged[,3])
            sum.df.i <- sum(df.i[,2]^2)
            sum.df.j <- sum(df.j[,2]^2)
            
            num <- 2 * sum(merged[, 2] * merged[, 3])
            den <- ((sum.df.i / (X^2) + sum.df.j / (Y^2)) * X * Y)
                
            coef.i.j <- num/den
            coef_matrix[i,j] <- coef.i.j
            }
        }
    }
    return(coef_matrix)
}


#Calculate the Jaccard Similarity Index for Overlap Analysis
jaccardIndex <- function(df, length, cloneCall, coef_matrix) {
  for (i in seq_along(length)){
    df.i <- df[[i]]
    df.i <- df.i[,c("barcode",cloneCall)]
    df.i_unique <- df.i[!duplicated(df.i[,cloneCall]),]
    for (j in seq_along(length)){
      if (i >= j){ next }
      else { 
        df.j <- df[[j]]
        df.j <- df.j[,c("barcode",cloneCall)]
        df.j_unique <- df.j[!duplicated(df.j[,cloneCall]),]
        overlap <- length(intersect(df.i_unique[,cloneCall], 
                                    df.j_unique[,cloneCall]))
        coef_matrix[i,j] <- 
          overlap/(sum(length(df.i_unique[,cloneCall]), 
                                  length(df.j_unique[,cloneCall]))-overlap)
      } 
    }
  }
  return(coef_matrix)
}

rawIndex <- function(df, length, cloneCall, coef_matrix) {
  for (i in seq_along(length)){
    df.i <- df[[i]]
    df.i <- df.i[,c("barcode",cloneCall)]
    df.i_unique <- df.i[!duplicated(df.i[,cloneCall]),]
    for (j in seq_along(length)){
      if (i >= j){ next }
      else { 
        df.j <- df[[j]]
        df.j <- df.j[,c("barcode",cloneCall)]
        df.j_unique <- df.j[!duplicated(df.j[,cloneCall]),]
        overlap <- length(intersect(df.i_unique[,cloneCall], 
                                    df.j_unique[,cloneCall]))
        coef_matrix[i,j] <- overlap
      } 
    }
  }
  return(coef_matrix)
}


#Calculate the Overlap Coefficient for Overlap Analysis
#' @author Nick Bormann, Nick Borcherding
overlapIndex <- function(df, length, cloneCall, coef_matrix) {
    for (i in seq_along(length)){
        df.i <- df[[i]]
        df.i <- df.i[,c("barcode",cloneCall)]
        df.i_unique <- df.i[!duplicated(df.i[,cloneCall]),]
        for (j in seq_along(length)){
            if (i >= j){ next }
            else { df.j <- df[[j]]
            df.j <- df.j[,c("barcode",cloneCall)]
            df.j_unique <- df.j[!duplicated(df.j[,cloneCall]),]
            overlap <- length(intersect(df.i_unique[,cloneCall], 
                                        df.j_unique[,cloneCall]))
            coef_matrix[i,j] <- 
                overlap/min(length(df.i_unique[,cloneCall]), 
                length(df.j_unique[,cloneCall])) } } }
    return(coef_matrix)
}

# This suppressing outputs for using dput()
quiet <- function(x) {
    sink(tempfile())
    on.exit(sink())
    invisible(force(x))
}

# This is to help sort the type of clonotype data to use
theCall <- function(x) {
    if (x %in% c("CTnt", "CTgene", "CTaa", "CTstrict")) {
      x <- x
    }else if (x == "gene" | x == "genes") {
        x <- "CTgene"
    } else if(x == "nt" | x == "nucleotide") {
        x <- "CTnt"
    } else if (x == "aa" | x == "amino") {
        x <- "CTaa"
    } else if (x == "gene+nt" | x == "strict") {
        x <- "CTstrict"
    }
    return(x)
}

# Assigning positions for TCR contig data
#' @author Gloria Kraus, Nick Bormann, Nick Borcherding
parseTCR <- function(Con.df, unique_df, data2) {
    for (y in seq_along(unique_df)){
        barcode.i <- Con.df$barcode[y]
        location.i <- which(barcode.i == data2$barcode)
        for (z in seq_along(location.i)) {
          where.chain <- data2[location.i[z],"chain"]
          if (where.chain == "TRA") {
            if(is.na(Con.df[y,"TCR1"])) {
              Con.df[y,tcr1_lines] <- data2[location.i[z],data1_lines]
            } else {
              Con.df[y,tcr1_lines] <- paste(Con.df[y, tcr1_lines],
                                            data2[location.i[z],data1_lines],sep=";") 
            }
          } else if (where.chain == "TRB") {
            if(is.na(Con.df[y,"TCR2"])) {
              Con.df[y,tcr2_lines] <- data2[location.i[z],data2_lines]
            } else {
              Con.df[y,tcr2_lines] <- paste(Con.df[y, tcr2_lines],
                                            data2[location.i[z],data2_lines],sep=";") 
            }
          }
        }
    }
  return(Con.df)
}

#Assigning positions for BCR contig data
#Now assumes lambda over kappa in the context of only 2 light chains
#' @author Gloria Kraus, Nick Bormann, Nick Borcherding
parseBCR <- function (Con.df, unique_df, data2) {
  for (y in seq_along(unique_df)) {
    barcode.i <- Con.df$barcode[y]
    location.i <- which(barcode.i == data2$barcode)
    if (length(location.i) == 2) {
      if (!is.na(data2[location.i[1], c("IGHct")])) {
        Con.df[y, heavy_lines] <- data2[location.i[1], h_lines]
        if(is.na(data2[location.i[2], c("IGHct")])) {
          if (!is.na(data2[location.i[2], c("IGLct")])) {
            Con.df[y, light_lines] <- data2[location.i[2], l_lines]
          } else if(!is.na(data2[location.i[2], c("IGKct")])) {
            Con.df[y, light_lines] <- data2[location.i[2], k_lines]
          }
        }
      } else if (!is.na(data2[location.i[2], c("IGHct")])) {
        Con.df[y, heavy_lines] <- data2[location.i[2], h_lines]
        if(is.na(data2[location.i[1], c("IGHct")])) {
          if (!is.na(data2[location.i[1], c("IGLct")])) {
            Con.df[y, light_lines] <- data2[location.i[1], l_lines]
          } else if(!is.na(data2[location.i[1], c("IGKct")])) {
            Con.df[y, light_lines] <- data2[location.i[1], k_lines]
          }
        }
      }
    }else if (length(location.i) == 1) {
      chain.i <- data2$chain[location.i]
      if (chain.i == "IGH") {
        Con.df[y, heavy_lines] <- data2[location.i[1], h_lines]
      }
      else if (chain.i == "IGL") {
        Con.df[y, light_lines] <- data2[location.i[1], l_lines]
      }
      else {
        Con.df[y, light_lines] <- data2[location.i[1], k_lines]
      }
    }
  }
  return(Con.df)
}

#Assign T/B cell chains and celltypes for combineTCR() and lengthContig
cellT <- function(cells) {
    if (cells == "T-AB") { 
        chain1 <- "TRA"
        chain2 <- "TRB" 
        cellType <- "T-AB" 
    } else if (cells == "T-GD") {
        chain1 <- "TRD"
        chain2 <- "TRG"
        cellType <- "T-GD" 
    } else if (cells == "B") {
        chain1 <- "IGH"
        chain2 <- "IGL"
        cellType <- "B" 
    }
    return(list(chain1, chain2, cellType))
}


#Producing a data frame to visualize for lengthContig()
lengthDF <- function(df, cloneCall, chain, group, c1, c2){
    Con.df <- NULL
    names <- names(df)
    if (chain == "both") {
            for (i in seq_along(df)) {
                length <- nchar(gsub("_", "", df[[i]][,cloneCall]))
                val <- df[[i]][,cloneCall]
                if (!is.null(group)) { 
                    cols <- df[[i]][,group]
                    data <- na.omit(data.frame(length, val, cols, names[i]))
                    colnames(data) <- c("length", "CT", group, "values")
                    Con.df<- rbind.data.frame(Con.df, data) 
                } else {
                    data <- na.omit(data.frame(length, val, names[i]))
                    colnames(data) <- c("length", "CT", "values")
                    Con.df<- rbind.data.frame(Con.df, data) }}
    } else if (chain != "both") {
            for (x in seq_along(df)) {
                df[[x]] <- off.the.chain(df[[x]], chain, cloneCall)
                strings <- df[[x]][,cloneCall]
                val1 <- strings
                for (i in seq_along(val1)) {
                    if (grepl(";", val1[i]) == TRUE) {
                        val1[i] <- str_split(val1[i], ";", simplify = TRUE)[1] 
                    } else { next() } }
                chain1 <- nchar(val1)
                if (!is.null(group)) {
                    cols1 <- df[[x]][,group]
                    data1 <- data.frame(chain1, val1, names[x], c1, cols1)
                    colnames(data1)<-c("length","CT","values","chain",group)
                }else if (is.null(group)){
                    data1 <- data.frame(chain1, val1, names[x], c1)
                    colnames(data1) <- c("length", "CT", "values", "chain")
                data <- na.omit(data1)
                data <- subset(data, CT != "NA" & CT != "")
                Con.df<- rbind.data.frame(Con.df, data) }}
    }
return(Con.df)}

#General combination of nucleotide, aa, and gene sequences for T/B cells
assignCT <- function(cellType, Con.df) {
    if (cellType %in% c("T-AB", "T-GD")) {
        Con.df$CTgene <- paste(Con.df$TCR1, Con.df$TCR2, sep="_")
        Con.df$CTnt <- paste(Con.df$cdr3_nt1, Con.df$cdr3_nt2, sep="_")
        Con.df$CTaa <- paste(Con.df$cdr3_aa1, Con.df$cdr3_aa2, sep="_")
        Con.df$CTstrict <- paste(Con.df$TCR1, Con.df$cdr3_nt1, 
            Con.df$TCR2, Con.df$cdr3_nt2, sep="_")
    } else {
        Con.df$CTgene <- paste(Con.df$IGH, Con.df$IGLC, sep="_")
        Con.df$CTnt <- paste(Con.df$cdr3_nt1, Con.df$cdr3_nt2, sep="_")
        Con.df$CTaa <- paste(Con.df$cdr3_aa1, Con.df$cdr3_aa2, sep="_") }
return(Con.df)
}


#Sorting the V/D/J/C gene sequences for T and B cells
#' @importFrom stringr str_c str_replace_na
#' @importFrom dplyr bind_rows
makeGenes <- function(cellType, data2, chain1, chain2) {
    if(cellType %in% c("T-AB", "T-GD")) {
        data2 <- data2 %>% 
            mutate(TCR1 = ifelse(chain == chain1, 
                  str_c(str_replace_na(v_gene),  str_replace_na(j_gene), str_replace_na(c_gene), sep = "."), NA)) %>%
            mutate(TCR2 = ifelse(chain == chain2, 
                  str_c(str_replace_na(v_gene), str_replace_na(d_gene),  str_replace_na(j_gene),  str_replace_na(c_gene), sep = "."), NA))
    }
    else {
        heavy <- data2[data2$chain == "IGH",] %>% 
          mutate(IGHct = str_c(str_replace_na(v_gene), str_replace_na(d_gene),  str_replace_na(j_gene),  str_replace_na(c_gene), sep = "."))
        kappa <- data2[data2$chain == "IGK",] %>% 
          mutate(IGKct = str_c(str_replace_na(v_gene),  str_replace_na(j_gene), str_replace_na(c_gene), sep = ".")) 
        lambda <- data2[data2$chain == "IGL",] %>%
          mutate(IGLct = str_c(str_replace_na(v_gene),  str_replace_na(j_gene), str_replace_na(c_gene), sep = "."))
        data2 <- bind_rows(heavy, kappa, lambda)
    }
    return(data2)
}

short.check <- function(df, cloneCall) {
  min <- c()
  for (x in seq_along(df)) {
    min.tmp <- length(which(!is.na(unique(df[[x]][,cloneCall]))))
    min <- c(min.tmp, min)
  }
  min <- min(min)
  return(min)
}

select.gene <- function(df, chain, gene, label) {
  if (chain %in% c("TRB", "TRG", "IGH")) {
    gene <- unname(c(V = 1, D = 2, J = 3, C = 4)[gene])
  } else {
    gene <- unname(c(V = 1, J = 2, C = 3)[gene])
  }
  if (ncol(str_split(df[,"CTgene"], "_", simplify = TRUE)) == 1) {
    C1 <- str_split(df[,"CTgene"], "_", simplify = TRUE)[,1] 
    C1 <- str_split(C1, "[.]", simplify = TRUE)[,gene] 
    df$C1 <- C1
    x <- "C1"
  } else {
    C1 <- str_split(df[,"CTgene"], "_", simplify = TRUE)[,1] 
    C1 <- str_split(C1, "[.]", simplify = TRUE)[,gene] 
    C2 <- str_split(df[,"CTgene"], "_", simplify = TRUE)[,2] 
    C2 <- str_split(C2, "[.]", simplify = TRUE)[,gene] 
    df$C1 <- C1
    df$C2 <- C2
    if (chain %in% c("TRA", "TRD", "IGH")) {
      x <- "C1"}
    else if (chain %in% c("TRB", "TRG", "IGL")) {
      x <- "C2"}
  }
  return(df)
}



#' Examining the clonal homeostasis
#'
#' This function calculates the space occupied by clonotype proportions. 
#' The grouping of these clonotypes is based on the parameter cloneTypes, 
#' at default, cloneTypes will group the clonotypes into bins of Rare = 0 
#' to 0.0001, Small = 0.0001 to 0.001, etc. To adjust the proportions, 
#' change the number or labeling of the cloneTypes paramter. If a matrix 
#' output for the data is preferred, set exportTable = TRUE.
#'
#' @examples
#' #Making combined contig data
#' x <- contig_list
#' combined <- combineTCR(x, rep(c("PX", "PY", "PZ"), each=2), 
#' rep(c("P", "T"), 3), cells ="T-AB")
#' clonalHomeostasis(combined, cloneCall = "gene")
#'
#' @param df The product of combineTCR(), combineBCR(), expression2List(), or combineExpression().
#' @param cloneTypes The cutpoints of the proportions.
#' @param cloneCall How to call the clonotype - VDJC gene (gene), 
#' CDR3 nucleotide (nt), CDR3 amino acid (aa), or 
#' VDJC gene + CDR3 nucleotide (strict).
#' @param chain indicate if both or a specific chain should be used - 
#' e.g. "both", "TRA", "TRG", "IGH", "IGL"
#' @param exportTable Exports a table of the data into the global 
#' environment in addition to the visualization
#' @import ggplot2
#' @importFrom stringr str_split
#' @importFrom reshape2 melt
#' @export
#' @return ggplot of the space occupied by the specific proportion of clonotypes
clonalHomeostasis_m <- function(df, cloneTypes = c(Rare = .0001, Small = .001, 
                        Medium = .01, Large = .1, Hyperexpanded = 1),
                        cloneCall = "strict", chain = "both", 
                        exportTable = FALSE) {
    cloneTypes <- c(cloneTypes)
    df <- list.input.return(df)
    cloneCall <- theCall(cloneCall)
    df <- checkList(df)
    df <- checkBlanks(df, cloneCall)
    mat <- matrix(0, length(df), length(cloneTypes) - 1, 
                dimnames = list(names(df), 
                names(cloneTypes)[-1]))
    if (chain != "both") {
      for (x in seq_along(df)) {
        df[[x]] <- off.the.chain(df[[x]], chain, cloneCall)
      }
    }
    df <- lapply(df, '[[', cloneCall)
    df <- lapply(df, na.omit)
    fun <- function(x) { table(x)/length(x) }
    df <- lapply(df, fun)
    for (i in 2:length(cloneTypes)) {
        mat[,i-1] <- vapply(df, function (x) sum(x[x > cloneTypes[i-1] & x <= 
                            cloneTypes[i]]), FUN.VALUE = numeric(1))
        colnames(mat)[i-1] <- paste0(names(cloneTypes[i]), ' (', 
                                    cloneTypes[i-1], ' < X <= ', 
                                    cloneTypes[i], ')') }
    if (exportTable == TRUE) { return(mat) }
    mat_melt <- melt(mat)
    col <- length(unique(mat_melt$Var2))
    order_mat <- mat_melt %>%
     filter(Var2 == "Small (1e-04 < X <= 0.001)") %>%
      arrange(value, desc = TRUE)
    o <- order_mat$Var1
    
    
    mat_melt <- mat_melt[mat_melt$Var1 %in% o,]    
 #   mat_melt$Var1 <- factor(mat_melt$Var1, levels = o)
    
    plot <- ggplot(mat_melt, aes(x=as.factor(Var1), y=value, fill=Var2)) +
        geom_bar(stat = "identity", position="fill", 
                    color = "black", lwd= 0.25) +
        scale_fill_manual(name = "Clonotype Group", 
                    values = c(  "#8c6bb1","#41b6c4", "#fec44f","#ce1256" )) +
        xlab("Samples") +
        ylab("Relative Abundance") +
        theme_void() +  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 20),axis.text.y = element_text(size = 20), legend.text = element_text(size = 20), axis.title = element_text(size=20), axis.title.y = element_text(angle = 90))

    return(plot)
}


```


## Open clonotype data
```{r clono, eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
# Run from raw BCR data stored in path_to_data or load the combined BCR data in the following chunk
# loading the data
vdj <- list()
dirs <- list.dirs(path = path_to_data, full.names = TRUE, recursive = FALSE)

samples <- c("NeoBCC007_post",
             "NeoBCC008_post",
             "NeoBCC012_post",
             "NeoBCC017_post",
             "NeoBCC004_post",
             "NeoBCC005_post",
             "NeoBCC006_post",
             "NeoBCC010_post",
             "NeoBCC011_post",
             "NeoBCC014_post",
             "NeoBCC015_post",
             "NeoBCC018_post")




for (i in (samples)){
  dir_TCR <- paste0(path_to_data, i, "_BCR_VDJ")
  vdj[[i]] <- read.csv(paste0(dir_TCR, "/filtered_contig_annotations.csv"))
}

head(vdj[[1]])

# combine the contigs
combined <- combineBCR(vdj, 
                samples = gsub("_pre|_post", "", samples), 
                removeNA = TRUE, removeMulti = TRUE)


merge_combined <- bind_rows(combined, .id = "sample")


# saveRDS(combined, "Ressler2018/metadata/100_CombinedBCR.Rds")
```



# Figure 3E
```{r echo=TRUE, fig.height=10, fig.width=20, message=FALSE, warning=FALSE, out.width='100%'}
combined <- readRDS("Ressler2018/metadata/100_CombinedBCR.Rds")

srat <- RenameCells(srat,new.names = paste0(srat$patient, "_",gsub("(_1|_2|_3|_4|_5|_6|_7|_8|_9)*", "",colnames(srat))))
srat <- RenameCells(srat,new.names = gsub("_post", "",colnames(srat)))

srat$sample <- gsub("_post", "",srat$patient)


seurat <- combineExpression(combined, srat, 
                  cloneCall = "strict", 
                  group.by = "sample", chain = "both",
                  proportion = TRUE,
                  filterNA = TRUE)



s   <- subset(seurat, subset = anno_l1 %in%  c("B cells","Plasma cells") )

#s@meta.data$anno_l1 <- droplevels(s@meta.data$anno_l1)
#s@meta.data$seurat_clusters <- droplevels(s@meta.data$seurat_clusters)

s@meta.data$cloneType <- factor(s@meta.data$cloneType, levels = unique(s$cloneType))

ss   <- subset(s, subset = anno_l1 %in% c("Plasma cells"))





colors = c("Small (1e-04 < X <= 0.001)"   = "#8c6bb1",
           "Medium (0.001 < X <= 0.01)"   = "#41b6c4",
           "Large (0.01 < X <= 0.1)"      = "#fec44f",
           "Hyperexpanded (0.1 < X <= 1)" = "#ce1256"
)



p <- SCpubr::do_DimPlot(sample = s, reduction = "umap", label = FALSE, repel = TRUE, label.color = "white", 
                         legend.position = "none", split.by = "cloneType", font.size = 12,pt.size = 1, ncol = 4, colors.use = colors)

p
p <- SCpubr::do_DimPlot(sample = s, reduction = "umap", label = FALSE, repel = TRUE, label.color = "white", 
                         legend.position = "none", group.by = "cloneType", font.size = 12,pt.size = 1, ncol = 4, colors.use = colors)



DT::datatable(p$data, 
              caption = ("Figure 3Eb"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```

# Figure 3Ea

```{r fig.height=6, fig.width=12, message=FALSE, warning=FALSE,  out.width='100%'}

combined_B <- lapply(combined, function(x) {x[x$barcode %in% colnames(s),] })
merge_combined_B <- bind_rows(combined_B, .id = "sample")


c_pCR <- combined_B[c("NeoBCC008",
           "NeoBCC007", 
           "NeoBCC012",
           "NeoBCC017" )]
p3 <- clonalHomeostasis_m(c_pCR, chain = "both") +
    theme(axis.text.x=element_blank())
p3$labels$x <- "pCR"


c_nonpCR <- combined_B[c( 
                        "NeoBCC010",
                        "NeoBCC014",
                        "NeoBCC011",
                        "NeoBCC004",
                        "NeoBCC005",
                        "NeoBCC018",
                        "NeoBCC006",
                        "NeoBCC015"
 )]
p4 <- clonalHomeostasis_m(c_nonpCR, chain = "both") +
    theme(axis.text.x=element_blank())
p4$labels$y <- " "
p4$labels$x <- "non-pCR"

p <- p3 + p4 + plot_layout(ncol = 2,  widths  = c(1,2),  guides = "collect")

p
DT::datatable(rbind(p3$data, p4$data), 
              caption = ("Figure 3Ea"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```



# Extended Data Figure 9c



```{r echo=TRUE, fig.height=7, fig.width=9, message=FALSE, warning=FALSE, out.width='100%'}

Idents(s) <- s$seurat_clusters

  tmp <- data.frame(grabMeta(s), identity = s$seurat_clusters, get.coord(s, "umap"))
 
    
  tmp$include <- ifelse(tmp$Frequency >= 0.1, "Yes", NA)
  tmp2 <- subset(tmp, include == "Yes")
  p1 <- ggplot(tmp2, mapping = aes(x=tmp2$UMAP_1, y = tmp2$UMAP_2)) +
    geom_point(tmp, mapping = aes(x=tmp$UMAP_1, y = tmp$UMAP_2, color = tmp[,"identity"]), size= 1) +
    geom_density_2d(color = "black", lwd=0.5, bins = 8) + 
    theme_minimal() +
    labs(color = "B cell subsets") +
     theme(text = element_text(size = 26), legend.key.width = unit(1, "cm"), legend.position = "right", legend.text = element_text(size=20)) + guides(colour = guide_legend(override.aes = list(size=8))) +
    scale_colour_manual(values = colors_B, breaks = levels(s$anno_l2)) +
    xlab("UMAP 1") + ylab("UMAP 2") + ggtitle(" Density of \n hyperexpanded") + ylim(-7,20) 
  p1
  
  DT::datatable(p1$data, 
              caption = ("Extended Data Figure 9Ca"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

   
  tmp <- data.frame(grabMeta(s), identity = s$seurat_clusters, get.coord(s, "umap"))
  tmp$include <- ifelse(tmp$Frequency >= 0.01 & tmp$Frequency <= 0.1 , "Yes", NA)
  tmp2 <- subset(tmp, include == "Yes")
  p2 <- ggplot(tmp2, mapping = aes(x=tmp2$UMAP_1, y = tmp2$UMAP_2)) +
    geom_point(tmp, mapping = aes(x=tmp$UMAP_1, y = tmp$UMAP_2, color = tmp[,"identity"]), size= 1) +
    geom_density_2d(color = "black", lwd=0.5, bins = 8) + 
    theme_minimal() +
    labs(color = "B cell subsets") +
     theme(text = element_text(size = 26), legend.key.width = unit(1, "cm"), legend.position = "right", legend.text = element_text(size=20)) + guides(colour = guide_legend(override.aes = list(size=8))) +
    scale_colour_manual(values = colors_B, breaks = levels(s$anno_l2)) +
    xlab("UMAP 1") + ylab("UMAP 2") + ggtitle(" Density of \n large clones") + ylim(-7,20) 
  p2
  
   DT::datatable(p2$data, 
              caption = ("Extended Data Figure 9Cb"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
  
  tmp <- data.frame(grabMeta(s), identity = s$seurat_clusters, get.coord(s, "umap"))
  tmp$include <- ifelse(tmp$Frequency >= 0.001 & tmp$Frequency <= 0.01 , "Yes", NA)
  tmp2 <- subset(tmp, include == "Yes")
  p3 <- ggplot(tmp2, mapping = aes(x=tmp2$UMAP_1, y = tmp2$UMAP_2)) +
    geom_point(tmp, mapping = aes(x=tmp$UMAP_1, y = tmp$UMAP_2, color = tmp[,"identity"]), size= 1) +
    geom_density_2d(color = "black", lwd=0.5, bins = 8) + 
    theme_minimal() +
    labs(color = "B cell subsets") +
     theme(text = element_text(size = 26), legend.key.width = unit(1, "cm"), legend.position = "right", legend.text = element_text(size=20)) + guides(colour = guide_legend(override.aes = list(size=8))) +
    scale_colour_manual(values = colors_B, breaks = levels(s$anno_l2)) +
    xlab("UMAP 1") + ylab("UMAP 2") + ggtitle(" Density of \n medium clones") + ylim(-7,20) 
  p3
  
   DT::datatable(p3$data, 
              caption = ("Extended Data Figure 9Cc"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
  
  tmp <- data.frame(grabMeta(s), identity = s$seurat_clusters, get.coord(s, "umap"))
  tmp$include <- ifelse(tmp$Frequency >= 0.0001 & tmp$Frequency <= 0.001 , "Yes", NA)
  tmp2 <- subset(tmp, include == "Yes")
  p4 <- ggplot(tmp2, mapping = aes(x=tmp2$UMAP_1, y = tmp2$UMAP_2)) +
    geom_point(tmp, mapping = aes(x=tmp$UMAP_1, y = tmp$UMAP_2, color = tmp[,"identity"]), size= 1) +
    geom_density_2d(color = "black", lwd=0.5, bins = 8) + 
    theme_minimal() +
    labs(color = "B cell subsets") +
     theme(text = element_text(size = 26), legend.key.width = unit(1, "cm"), legend.position = "right", legend.text = element_text(size=20)) + guides(colour = guide_legend(override.aes = list(size=8))) +
    scale_colour_manual(values = colors_B, breaks = levels(s$anno_l2)) +
    xlab("UMAP 1") + ylab("UMAP 2") + ggtitle(" Density of \n small clones") + ylim(-7,20) 
  
p4

 DT::datatable(p4$data, 
              caption = ("Extended Data Figure 9Cd"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
  
 
   
```



# Extended Data Figure 9D


```{r  fig.height=6.5, fig.width=25, message=FALSE, warning=FALSE,  out.width='100%'}
q1 <- quantContig(combined_B, cloneCall="gene+nt", exportTable = TRUE)


q1$Response <- "non-pCR"
q1$patient <- q1$values
q1$Response[grepl("NeoBCC007|NeoBCC008|NeoBCC012|NeoBCC017", q1$values)] <- "pCR"
q1$Response <- factor(q1$Response, levels = c("pCR", "non-pCR"))
q1$percent <- q1$contigs / q1$total * 100


g1 <- ggpaired(q1, x = "Response", y = "total", id="patient", color = "black", fill = "Response" , palette= c("#66c2a4", "#ccece6"), point.size = 2, xlab = "Response", ylab = " Number of \n BCR clonality") + stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = 4500, hide.ns = FALSE, label = "p.format", label.x.npc = "center", bracket.size = 1, comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size = 8)  +theme(text = element_text(size = 30), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylim(c(0, 5000)) & NoLegend()

DT::datatable(g1$data, 
              caption = ("Extended Data Figure 9Da-c"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


g2 <- ggpaired(q1, x = "Response", y = "percent", id="patient", color = "black", fill = "Response" ,  palette= c("#66c2a4", "#ccece6"), point.size = 2, xlab = "Response", ylab = " Relative % \n of unique clonotypes") + stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = 100, hide.ns = FALSE, label = "p.format", label.x.npc = "center", bracket.size = 1, comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size = 8)  +theme(text = element_text(size = 30), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  + ylim(c(0, 110)) & NoLegend()




g3 <- ggpaired(q1, x = "Response", y = "contigs", id="patient",  color = "black", fill = "Response" ,  palette= c("#66c2a4", "#ccece6"), point.size = 2, xlab = "Response", ylab = " Number of \n unique clonotypes") + stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = 900, hide.ns = FALSE, label = "p.format", label.x.npc = "center", bracket.size = 1, comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size = 8)  +theme(text = element_text(size = 30), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + ylim(c(0, 1000)) & NoLegend()



norm_entropy <- function(observations) {
  observations <- observations[!is.na(observations)]
  p <- as.numeric(table(observations)) / length(observations)
  n <- length(p)
  if (n == 1) {
    return(0)
  }
  h <- -sum(p*log(p))
  h_max <- log(length(observations))
  return(h / h_max)
}
clonality <- rep(NA, length(names(combined_B)))
names(clonality) <- names(combined_B)
for (p in names(combined_B)){
clonality[p] <- norm_entropy(combined_B[[p]]$CTaa)
}

clonality <- as.data.frame(clonality)

clonality$Response <- "non-pCR"
clonality$Response[grepl("NeoBCC007|NeoBCC008|NeoBCC012|NeoBCC017", rownames(clonality))] <- "pCR"
clonality$Response <- factor(clonality$Response, levels = c("pCR", "non-pCR"))
clonality$patient <- rownames(clonality)
g4 <- ggpaired(clonality, x = "Response", y = "clonality", id="patient",  color = "black", fill = "Response" , palette= c("#66c2a4", "#ccece6"), point.size = 2, xlab = "Response", ylab = "Repertoire clonality") + stat_compare_means( method = "wilcox.test", paired = FALSE, label.y = 1, hide.ns = FALSE, label = "p.format", label.x.npc = "center", bracket.size = 1, comparison = list(c("CR", "SD"), c("SD", "PR"), c("CR", "PR")), size = 8)  +theme(text = element_text(size = 30), axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))  + ylim(c(0, 1.10)) & NoLegend()

DT::datatable(g4$data, 
              caption = ("Extended Data Figure 9Dd"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


g <- g1 + g3 +g2 + g4 + plot_layout(ncol=4, guides="collect")
g
```






# Figure 3F

```{r fig.height=8, fig.width=15, message=FALSE, warning=FALSE, out.width='100%'}

genes <- list( 
               "Hyperexpanded" = c("HSBP1", "CSTB","CAP1", "SKP1"),
               "Large"  = c( "DPEP1","P2RX1"),
               "Medium" = c("RAPGEF1", "FBXW7", "FAM30A"),
               "Small"  = c("SOCS3", "UQCRC2","ITM2B",  "DDIT4")
               )

p <- SCpubr::do_DotPlot(sample = s, 
                   features = genes,
                   group.by = "cloneType",
                   font.size = 30, 
                   legend.length = 20,  
                   legend.type = "colorbar", 
                   dot.scale = 10,  
                   colors.use = c('#fee08b',"#ffffbf", "#f7f7f7","#c2a5cf", "#542788"))

p
DT::datatable(p$data, 
              caption = ("Figure 3F"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```

# Figure 3I



```{r fig.height=7, fig.width=25, echo=TRUE, message=FALSE, warning=FALSE, out.width='100%'}
ss@meta.data$cloneType <- factor(ss@meta.data$cloneType, levels = c("Hyperexpanded (0.1 < X <= 1)", "Large (0.01 < X <= 0.1)", "Medium (0.001 < X <= 0.01)", "Small (1e-04 < X <= 0.001)"))

# define cell group membership
Idents(ss) <- ss$cloneType

de_markers <- DElegate::FindAllMarkers2(ss, replicate_column = "patient", method = "edger", min_fc = 0, min_rate = 0.1)

signature_h <- de_markers$feature[de_markers$group1=="Hyperexpanded (0.1 < X <= 1)" ]
background <- rownames(s)
library(msigdbr)
library(clusterProfiler)
# enricher for cnet plot
GO_H_gene_sets = msigdbr(species = "human", category = "H")
msigdbr_t2g = GO_H_gene_sets %>% dplyr::distinct(gs_name, gene_symbol) %>% as.data.frame()

ego_h <- enricher(gene = signature_h, universe = background, TERM2GENE = msigdbr_t2g)

 
b <- barplot(ego_h, title = "Hallmarksenrichment of hyperexpanded clones")


tmp <- b$data

tmp$ID <- str_trunc(tmp$ID, 100, "right")
tmp$ID <- factor(tmp$ID, levels = tmp$ID[order(tmp$Count)])

p <- ggplot(tmp, aes(Count, ID)) +
    geom_bar(stat = "identity", color="black", fill =  colors["Hyperexpanded (0.1 < X <= 1)"]) +
   theme_classic()+ 
    geom_text(
        aes(label = (paste( "padj=", format(p.adjust,scientific = TRUE, digits = 2)))),
        color = "black",
        size = 6,
        hjust=1,
        position = position_dodge(0.5)  ) +
     theme(text = element_text(size=18)) +
  ggtitle("Hyperexpanded clones")


p
DT::datatable(p$data, 
              caption = ("Figure 3I"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

```








# Figure 3G


done on the highly confident B and plasma cells with exactly 2 IGH and IGL chains

```{r Fig_5_IgSwitch_UMAP, fig.height=10, fig.width=30, message=FALSE, warning=FALSE,  out.width='100%'}

df <- s@meta.data

df <- df %>% 
    separate( CTgene, c("IGH", "IGL"), sep = "_") %>%
  separate( IGH, c("V", "D", "J", "C"), "\\.")
   
 
s <- AddMetaData(s, df$C, col.name = "Ig_level")
ss <- subset(s, subset = Ig_level != "NA")
dim(ss)
colors = c("IGHA1" = "#addd8e",
           "IGHA2" = "#238443",
           "IGHM"  = "#dd3497" , 
           "IGHD"  =  "#41b6c4",
           "IGHG1" = "#fec44f",
           "IGHG2" = "#fe9929",
           "IGHG3" = "#ec7014",
           "IGHG4" = "#fee391"
)

ss@meta.data$Ig_level <- factor(ss@meta.data$Ig_level, levels = c("IGHA1",
         "IGHA2",
         "IGHM", 
         "IGHD",
         "IGHG1",
         "IGHG2",
         "IGHG3",
         "IGHG4"))


 

q1 <- SCpubr::do_BarPlot( ss,
                         group.by = "Ig_level",
                         split.by = "anno_l1",
                         position = "fill",
                         flip = TRUE,
                         order=FALSE,
                         legend.position = "right",
                         font.size = 30     , 
                         colors.use = colors) +
  xlab("") +
  ylab("Frequency of Ig isotypes")



q1
DT::datatable(q1$data, 
              caption = ("Figure 3Gb"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))




q1 <- SCpubr::do_BarPlot( ss,
                         group.by = "Ig_level",
                         split.by = "cloneType",
                         position = "fill",
                         flip = TRUE,
                         order=FALSE,
                         legend.position = "right",
                         font.size = 30     , 
                         colors.use = colors               ) +
  xlab("") +
  ylab("Frequency of Ig isotypes")



q1
DT::datatable(q1$data, 
              caption = ("Figure 3Ga"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```
