---
title: "Extended Data Figure 4"
author: '`r Sys.info()["user"]`'
date: '`r format(Sys.time(), "%B %d, %Y %H:%M:%S %Z")`'
output:
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    highlight: pygments
    df_print: kable
params:
  sample_name: ~
  sample_path: ~
  out_rds_path: ~
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	dev = c("png", "jpeg", "pdf")
)
```




```{r lib}
library(hdf5r)
library(Seurat)
library(SoupX)
library(canceRbits)
library(dplyr)
library(patchwork)
library(DT)
library(Azimuth)
library(SCpubr)
library(tibble)
library(dittoSeq)
library(scRepertoire)
library(reshape2)
library(viridis)
library(grDevices)
library(ggpubr)
library(ggplot2)
library(data.table)
library(msigdbr)
library(clusterProfiler)
library(org.Hs.eg.db)
library(tidyverse)
library(enrichplot)
library(RColorBrewer)
```



# Open corrected counts and annotated seurat object
Load the corrected (SoupX), normalized (SCTransformed) and annotated (Twice mapped - Tabula Sapiens Skin reference and PBMC azimuth reference) data.
```{r echo=FALSE, message=FALSE, warning=FALSE, out.width='100%'}
srat <- readRDS( "20241005_Ressler2024_NeoBCC.Rds")
meta <- srat@meta.data
meta$WHO <- "SD"
meta$WHO[meta$patient %in% c("NeoBCC007_post", "NeoBCC008_post", "NeoBCC012_post", "NeoBCC017_post")] <- "CR"
meta$WHO[meta$patient %in% c("NeoBCC004_post", "NeoBCC006_post", "NeoBCC010_post", "NeoBCC011_post")] <- "PR"
srat <- AddMetaData(srat, meta$WHO, col.name = "WHO")
srat$WHO <- factor(srat$WHO, levels = c("CR", "PR", "SD"))
```

# Seurat workflow with cell cycle regression


```{r include=FALSE}
set.seed <- 12345
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes

srat <- CellCycleScoring(srat, s.features = s.genes, g2m.features = g2m.genes, set.ident = FALSE)

srat    <- SCTransform(srat, verbose = F,vars.to.regress = c("S.Score", "G2M.Score"), conserve.memory = TRUE)
srat$old_seurat <- srat$seurat_clusters

vf <- VariableFeatures(srat)
exclude <- grepl('^IG', vf)
VariableFeatures(srat) <- vf[!exclude]

srat    <- RunPCA(srat, verbose = F)
srat    <- RunUMAP(srat, dims = 1:30, verbose = F, )
srat    <- FindNeighbors(srat, dims = 1:30, verbose = F)
srat    <- FindClusters(srat, verbose = T)


```

```{r echo=FALSE, fig.height=25, fig.width=25, message=FALSE, warning=FALSE, out.width='100%'}
srat@meta.data$anno_l1 <- factor(srat@meta.data$anno_l1, levels=c("other",
                                                                 "Mast cells",
                                                                 "Mono-Mac",
                                                                 "LC",
                                                                 "DC",
                                                                 "pDC",
                                                                 "Plasma cells",
                                                                 "B cells" ,
                                                                 "Proliferating cells",
                                                                 "Natural killer cells",
                                                                 "CD8+ T cells",
                                                                 "Tregs",
                                                                  "CD4+ T cells" ,
                                                                 "Melanocytes",
                                                                 "Endothelial cells",
                                                                 "Fibroblasts",
                                                                 "Keratinocytes",
                                                                 "Malignant cells"))
colors <- c("Malignant cells" = "#bd0026",
           "Keratinocytes" = "#dfc27d",
           "Fibroblasts" = "#f6e8c3",
           "Endothelial cells" = "#54278f",
           "Melanocytes" = "#a65628",
           "CD4+ T cells" = "#b8e186",
           "Tregs" = "#ae017e",
           "CD8+ T cells" = "#fbb4ae",
           "Proliferating cells" = "#b3cde3",
           "Natural killer cells" = "#9e9ac8",
           "B cells" = "#7bccc4",
           "Plasma cells" = "#35978f",
           "pDC" = "#fe9929",
           "DC" = "#e7298a",
           "LC" = "yellow" ,
           "Mono-Mac" = "#fec44f",
           "Mast cells" = "#bf812d",
           "other" = "#bdbdbd")

```

# Extended Data Figure 4c

```{r , eval=TRUE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE,  out.width='100%'}

p1 <- SCpubr::do_DimPlot(sample = srat, 
                   group.by = "anno_l1", 
                   pt.size=0.5, 
                   colors.use = colors,
                   label = TRUE, repel = TRUE, 
                   legend.position = "none",  
                   label.color = "black") + theme_minimal() + NoLegend() + theme(text = element_text(size=20)) +
  ggtitle(" UMAP after \n cell cycle regression")



DT::datatable(p1$data, 
              caption = ("Extended Data Figure 4c1"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


s <- subset(srat, subset = anno_l1 == "Proliferating cells")


p2 <- SCpubr::do_DimPlot(sample = s, 
                   group.by = "anno_l1", 
                   pt.size=0.5, 
                   colors.use = colors,
                   label = TRUE, repel = TRUE, 
                   legend.position = "none",  
                   label.color = "black") + theme_minimal() + NoLegend() + theme(text = element_text(size=20)) +
  ggtitle(" Proliferating cells after \n cell cycle regression")



DT::datatable(p2$data, 
              caption = ("Extended Data Figure 4c2"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```

```{r Azimuth2, eval=FALSE, error=TRUE, include=FALSE}
Idents(srat) <- srat$anno_l1
ref <- subset(srat, subset = anno_l1 != "Proliferating cells")
anchors <- FindTransferAnchors(reference = ref, query = s, dims = 1:30,
    reference.reduction = "pca")
predictions <- TransferData(anchorset = anchors, refdata = ref$anno_l1, dims = 1:30)
s <- AddMetaData(s, metadata = predictions$predicted.id, col.name = "prediction")

```

```{r , eval=TRUE, fig.height=8, fig.width=25, message=FALSE, warning=FALSE,  out.width='100%'}



p3 <- SCpubr::do_DimPlot(sample = s, 
                   group.by = "prediction", 
                   pt.size=0.5, 
                   colors.use = colors,
                   label = TRUE, repel = TRUE, 
                   legend.position = "none",  
                   label.color = "black") + theme_minimal() + NoLegend() + theme(text = element_text(size=20)) +
  ggtitle(" Proliferating cells after \n cell cycle regression")



DT::datatable(p3$data, 
              caption = ("Extended Data Figure 4c3"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))

p1 + p2 + p3


```


# Figure 4c4

```{r, fig.height=8, fig.width=12, message=FALSE, warning=FALSE, out.width='100%'}

q1 <- SCpubr::do_BarPlot( s,
                         group.by = "prediction",
                         split.by = "WHO",
                         position = "stack",
                         flip = TRUE,
                         order=FALSE,
                         legend.position = "none",
                         font.size = 32 ,
                         colors.use = colors,
                         xlab = "",
                         ylab = ""
                          
                   ) + xlab("Response") + ylab("Number of proliferating cells")


q1

DT::datatable(q1$data, 
              caption = ("Extended Data Figure Figure 4d"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```


```{r , fig.height=8, fig.width=12, message=FALSE, warning=FALSE,  out.width='100%'}


q2 <- SCpubr::do_BarPlot( s,
                         group.by = "prediction",
                         split.by = "Pathological.Response",
                         position = "stack",
                         flip = TRUE,
                         order=FALSE,
                         legend.position = "none",
                         font.size = 32 ,
                         colors.use = colors,
                         xlab = "",
                         ylab = ""
                          
                   ) + xlab("Response") + ylab("Number of proliferating cells")


q2

DT::datatable(q2$data, 
              caption = ("Extended Data Figure Figure 4e"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))


```