---
title: "Figures 2"
author: '`r Sys.info()["user"]`'
date: '`r format(Sys.time(), "%B %d, %Y %H:%M:%S %Z")`'
output:
  html_document: 
    toc: yes
    toc_float: yes
    code_folding: hide
    highlight: pygments
    df_print: kable
params:
  sample_name: ~
  sample_path: ~
  out_rds_path: ~
---

```{r setup, include=TRUE}
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE,
	dev = c("png", "jpeg", "pdf")
)
```




```{r lib}
library(hdf5r)
library(Seurat)
library(SoupX)
library(canceRbits)
library(dplyr)
library(patchwork)
library(DT)
library(Azimuth)
library(SCpubr)
library(tibble)
library(dittoSeq)
library(scRepertoire)
library(reshape2)
library(viridis)
library(grDevices)
library(ggpubr)
library(ggplot2)

```



# Open corrected counts and annotated seurat object
Load the corrected (SoupX), normalized (SCTransformed) and annotated (Twice mapped - Tabula Sapiens Skin reference and PBMC azimuth reference) data.
```{r echo=TRUE, message=FALSE, warning=FALSE, out.width='100%'}
srat <- readRDS( "20241005_Ressler2024_NeoBCC.Rds")
meta <- srat@meta.data
meta$WHO <- "SD"
meta$WHO[meta$patient %in% c("NeoBCC007_post", "NeoBCC008_post", "NeoBCC012_post", "NeoBCC017_post")] <- "CR"
meta$WHO[meta$patient %in% c("NeoBCC004_post", "NeoBCC006_post", "NeoBCC010_post", "NeoBCC011_post")] <- "PR"
srat <- AddMetaData(srat, meta$WHO, col.name = "WHO")
srat$WHO <- factor(srat$WHO, levels = c("CR", "PR", "SD"))

```

# Define levels and colors


```{r echo=TRUE, fig.height=25, fig.width=25, message=FALSE, warning=FALSE, out.width='100%'}
srat@meta.data$anno_l1 <- factor(srat@meta.data$anno_l1, levels=c("other",
                                                                 "Mast cells",
                                                                 "Mono-Mac",
                                                                 "LC",
                                                                 "DC",
                                                                 "pDC",
                                                                 "Plasma cells",
                                                                 "B cells" ,
                                                                 "Proliferating cells",
                                                                 "Natural killer cells",
                                                                 "CD8+ T cells",
                                                                 "Tregs",
                                                                  "CD4+ T cells" ,
                                                                 "Melanocytes",
                                                                 "Endothelial cells",
                                                                 "Fibroblasts",
                                                                 "Keratinocytes",
                                                                 "Malignant cells"))
colors <- c("Malignant cells" = "#bd0026",
           "Keratinocytes" = "#dfc27d",
           "Fibroblasts" = "#f6e8c3",
           "Endothelial cells" = "#54278f",
           "Melanocytes" = "#a65628",
           "CD4+ T cells" = "#b8e186",
           "Tregs" = "#ae017e",
           "CD8+ T cells" = "#fbb4ae",
           "Proliferating cells" = "#b3cde3",
           "Natural killer cells" = "#9e9ac8",
           "B cells" = "#7bccc4",
           "Plasma cells" = "#35978f",
           "pDC" = "#fe9929",
           "DC" = "#e7298a",
           "LC" = "yellow" ,
           "Mono-Mac" = "#fec44f",
           "Mast cells" = "#bf812d",
           "other" = "#bdbdbd")

```


# Figure 2E UMAP

```{r Fig2E, eval=TRUE, fig.height=8, fig.width=8, message=FALSE, warning=FALSE,  out.width='100%'}

p <- SCpubr::do_DimPlot(sample = srat, 
                  colors.use = colors, 
                  group.by = "anno_l1", 
                  pt.size=0.5, label = TRUE, 
                  repel = TRUE, 
                  legend.position = "none",  
                  label.color = "black") + 
     theme_minimal() + 
     NoLegend() + 
     theme(text = element_text(size=20))

p
DT::datatable(p$data, 
              caption = ("Figure 2E"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```



# Figure 2F Buble plots

```{r Fig2F, eval=TRUE, fig.height=12, fig.width=28, message=FALSE, warning=FALSE,  out.width='100%'}
genes <- list( 
               "Mal." = c("KRT17", "EPCAM", "BCAM"),
               "Kerati." = c("FGFBP1", "KRT1", "KRT6A"),
               "Fibro." = c("COL1A1", "COL1A2", "COL6A2"),
               "E" = c("VWF"),
               "Mel" = c("MLANA", "PMEL"),
               "CD4+T" = c("CD3E","CD2", "CD4"  ),
               "Tregs" = c("IL2RA", "CD25", "FOXP3", "TNFRSF4"),
               "CD8+T" = c("CD8A", "GZMA"),
               "NK" = c( "KLRC1", "PRF1", "GNLY"),
               "P" = c("MKI67"),
               "B" = c("MS4A1", "CD19"),
               "Plasma" = c("IGKC", "CD38", "SDC1"),
               "pDC" = c( "IRF8", "CLEC4C"),
               "DC" = c("LAMP3", "CCR7"),
               "LC" = c("CD1A", "CD207"),
               "Mono-Mac" = c("CD68",  "CD14" ),
               "Mast" = c("KIT", "SOCS1"))


p <- SCpubr::do_DotPlot(sample = srat,  
                        features = genes, 
                        group.by = "anno_l1",
                        font.size = 25, 
                        legend.length = 4,  
                        legend.type = "colorbar", 
                        dot.scale = 8,  
                        colors.use = c("#7fbc41","#b8e186", "#f7f7f7","#fde0ef", "#c51b7d"))
p
DT::datatable(p$data, 
              caption = ("Figure 2F"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```


# Figure 2G


```{r Fig2G, fig.height=8, fig.width=20, message=FALSE, warning=FALSE,  out.width='100%'}
# Subset immune / non-immune cells
imm <- subset(srat, subset = anno_l1 %in% c("other",
                                                                 "Mast cells",
                                                                 
                                                                 "Mono-Mac",
                                                                 "LC",
                                                                 "DC",
                                                                 "pDC",
                                                                 "Plasma cells",
                                                                 "B cells" ,
                                                                 "Proliferating cells",
                                                                 "Natural killer cells",
                                                                 "CD8+ T cells",
                                                                 "Tregs",
                                                                  "CD4+ T cells" ))


other <- subset(srat,subset = anno_l1 %in% c("Malignant cells",
                                                                 "Keratinocytes",
                                                                 "Fibroblasts",
                                                                 "Endothelial cells",
                                                                 "Melanocytes"))

imm$anno_l1 <- droplevels(imm$anno_l1)
other$anno_l1 <- droplevels(other$anno_l1)

# subset pCR and nonpCR for each subset

pCR_imm <- subset(imm, subset = Pathological.Response == "pCR" )

nonpCR_imm <- subset(imm, subset = Pathological.Response == "non-pCR")

pCR_other <- subset(other, subset = Pathological.Response == "pCR" )

nonpCR_other <- subset(other, subset = Pathological.Response == "non-pCR")


### plots

d1 <- SCpubr::do_BarPlot(pCR_other,
                         group.by = "anno_l1",
                         split.by = "patient",
                         position = "fill",
                         order=FALSE,
                         legend.position = "none",
                   flip = TRUE,
                   font.size = 14,
                   colors.use = colors,
                   ylab = "CD45- EPCAM+")

d2 <- SCpubr::do_BarPlot(nonpCR_other,
                         group.by = "anno_l1",
                         split.by = "patient",
                         position = "fill",
                         order=FALSE,
                         legend.position = "none",
                   flip = TRUE,
                   font.size = 14,
                   colors.use = colors,
                   ylab = "CD45- EPCAM+")



d3 <- SCpubr::do_BarPlot(pCR_imm,
                         group.by = "anno_l1",
                         split.by = "patient",
                         position = "fill",
                         order=FALSE,
                         legend.position = "none",
                   flip = TRUE,
                   font.size = 20,
                   colors.use = colors,
                   ylab = "CD45+ EPCAM-")

d4 <- SCpubr::do_BarPlot(nonpCR_imm,
                         group.by = "anno_l1",
                         split.by = "patient",
                         position = "fill",
                         order=FALSE,
                         legend.position = "none",
                   flip = TRUE,
                   font.size = 20,
                   colors.use = colors,
                   ylab = "CD45+ EPCAM-")





p <- d3 +  d4  + plot_layout(ncol = 1, heights = c(1,2))
p
DT::datatable(d3$data, 
              caption = ("Figure 2Ga"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
DT::datatable(d4$data, 
              caption = ("Figure 2Gb"),
              extensions = 'Buttons', 
              options = list( dom = 'Bfrtip',
              buttons = c( 'csv', 'excel')))
```
